version: "3"
services:
  breach-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - hmpps
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
    networks:
      - hmpps
  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "8072:3000"
    networks:
      - hmpps
  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: localstack-external
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

networks:
  hmpps:
